export class BillingDetail{
    id: number;
  appCode: any;
  requesterBy: any;
  requesterCode: any;
  requesterMob: any;
  reqdate: any;
  reqtime: any;
  noofperson: number;
  vehicleShareIdicater: any;
  vehicleShareIdicaterId: number;
  vehicleNo: any;
  vehiclehiredinhouse: any;
  vehiclevendorcode: any;
  vehiclevendorname: any;
  startKM: number;
  endKM: number;
  totalRuningKM: number;
  totalAmountKMBased: number;
  paybaleAmount: number;
  driverCode: any;
  requestattime:any;
  driverhiredinhouse: any;
  driverName: any;
  driverMobile: any;
  startDate: any;
  startTime: any;
  endDate: any;
  endTime: any;
  expetdate:any;
  expettime:any;
  billDate: any;
  appstatus: any;
  requestTypeName: any;
  trainno: any;
  trainname: any;
  vehiclereqwhere: any;
  visitingplace: any;
  purpose: any;
  statusdetails: any;
 
}